sudo: true
os:
- linux
language:
- node_js
node_js:
- '9'
cache: false
env:
  global:
  - JWTKEYFILE=assets/server.key
before_install:
- openssl aes-256-cbc -K $encrypted_bb5f45c25311_key -iv $encrypted_bb5f45c25311_iv -in key.pem.enc -out ~\/JWT/tnoonan/2018/key.pem -d
- scripts/before_install.sh
script:
- scripts/script.sh
