sudo: true
os:
  - linux
language:
  - node_js
node_js:
  - "9"
cache: false
env:
  global: 
    - JWTKEYFILE=assets/server.key
    - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
  - scripts/before_install.sh
script:
  - scripts/script.sh
