sudo: true
os:
- linux
language:
- node_js
node_js:
- '9'
cache: false
env:
  global:
  - JWTKEYFILE=assets/key.pem
before_install:
- openssl aes-256-cbc -K $encrypted_bb5f45c25311_key -iv $encrypted_bb5f45c25311_iv -in assets/key.pem.enc -out assets/key.pem -d
- scripts/before_install.sh
script:
- scripts/script.sh
